services:
  postgres:
    image: postgres:16-alpine
    container_name: realstate-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: realstate
      POSTGRES_PASSWORD: realstate123
      POSTGRES_DB: realstate
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./uploads:/app/uploads

volumes:
  postgres_data:
